language: ruby
rvm:
 - 2.5.0
addons:
  postgresql: 10
  chrome: stable
script:
 - bundle exec rails db:migrate RAILS_ENV=test
 - bundle exec rspec
before_install:
  - gem update --system
  - gem install bundler