language: ruby
rvm:
 - 2.5.0
services:
  - postgresql
script:
 - bundle exec rails db:migrate RAILS_ENV=test
 - bundle exec rspec
before_install:
  - gem update --system
  - gem install bundler
  - psql -c 'create database concurrently_test;' -U postgres
