development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: streaming_logs_dev

test:
  adapter: redis

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: streaming_logs_production
